security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: username
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
               login_path: login
               check_path: login
               provider: my_provider

            logout:
                path: /logout
                target: /login


    access_control:
         - { path: ^/login, roles: ROLE_ADMIN }
         - { path: ^/userlist, roles: ROLE_ADMIN }
         - { path: ^/register, roles: ROLE_ADMIN }
         - { path: ^/postlist, roles: ROLE_ADMIN }
         - { path: ^/index, roles: ROLE_ADMIN }

         - { path: ^/login, roles: ROLE_USER }
         - { path: ^/register, roles: ROLE_USER }
         - { path: ^/postlist, roles: ROLE_USER }
         - { path: ^/index, roles: ROLE_USER }
