security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: name
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
               login_path: login
               check_path: login
               provider: my_provider

            logout:
                path: /logout
                target: /login


    access_control:

    - { path: ^/userlist, roles: ROLE_ADMIN }

    - { path: ^/postlist, roles: ROLE_USER }
    #- { path: ^/createPost, roles: ROLE_USER }

    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }